# Generated by Django 3.0.8 on 2020-08-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YKS', '0002_auto_20200815_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_ea_2018_ham',
            field=models.TextField(default=1, max_length=8, verbose_name='ayt_sir_ea_2018_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_ea_2018_yer',
            field=models.TextField(default=1, max_length=8, verbose_name='ayt_sir_ea_2018_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_ea_2019_ham',
            field=models.TextField(default=1, max_length=8, verbose_name='ayt_sir_ea_2019_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_ea_2019_yer',
            field=models.TextField(default=1, max_length=8, verbose_name='ayt_sir_ea_2019_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sayisal_2018_ham',
            field=models.TextField(default=1, max_length=8, verbose_name='ayt_sir_sayisal_2018_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sayisal_2018_yer',
            field=models.TextField(default=1, max_length=8, verbose_name='ayt_sir_sayisal_2018_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sayisal_2019_ham',
            field=models.TextField(default=1, max_length=8, verbose_name='ayt_sir_sayisal_2019_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sayisal_2019_yer',
            field=models.TextField(default=1, max_length=8, verbose_name='ayt_sir_sayisal_2019_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sozel_2018_ham',
            field=models.TextField(default=1, max_length=8, verbose_name='ayt_sir_sozel_2018_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sozel_2018_yer',
            field=models.TextField(default=1, max_length=8, verbose_name='ayt_sir_sozel_2018_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sozel_2019_ham',
            field=models.TextField(default=1, max_length=8, verbose_name='ayt_sir_sozel_2019_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sozel_2019_yer',
            field=models.TextField(default=1, max_length=8, verbose_name='ayt_sir_sozel_2019_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='tyt_sir_2018_ham',
            field=models.TextField(default=1, max_length=8, verbose_name='tyt_sir_2018_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='tyt_sir_2018_yer',
            field=models.TextField(default=1, max_length=8, verbose_name='tyt_sir_2018_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='tyt_sir_2019_ham',
            field=models.TextField(default=1, max_length=8, verbose_name='tyt_sir_2019_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='tyt_sir_2019_yer',
            field=models.TextField(default=1, max_length=8, verbose_name='tyt_sir_2019_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ydt_sir_2018_ham',
            field=models.TextField(default=1, max_length=8, verbose_name='ydt_sir_2018_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ydt_sir_2018_yer',
            field=models.TextField(default=1, max_length=8, verbose_name='ydt_sir_2018_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ydt_sir_2019_ham',
            field=models.TextField(default=1, max_length=8, verbose_name='ydt_sir_2019_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ydt_sir_2019_yer',
            field=models.TextField(default=1, max_length=8, verbose_name='ydt_sir_2019_yer'),
        ),
    ]
