# Generated by Django 3.0.8 on 2020-08-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YKS', '0003_auto_20200815_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yks',
            name='eaham',
            field=models.FloatField(default=500, max_length=3, verbose_name='Eaham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='eayer',
            field=models.FloatField(default=500, max_length=3, verbose_name='Eayer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='sayisalham',
            field=models.FloatField(default=500, max_length=3, verbose_name='Sayisalham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='sayisalyer',
            field=models.FloatField(default=500, max_length=3, verbose_name='Sayisalyer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='sozelham',
            field=models.FloatField(default=500, max_length=3, verbose_name='Sozelham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='sozelyer',
            field=models.FloatField(default=500, max_length=3, verbose_name='Sozelyer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='tyt_sir_2018_ham',
            field=models.FloatField(default=1, max_length=8, verbose_name='tyt_sir_2018_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='tyt_sir_2018_yer',
            field=models.FloatField(default=1, max_length=8, verbose_name='tyt_sir_2018_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='tyt_sir_2019_ham',
            field=models.FloatField(default=1, max_length=8, verbose_name='tyt_sir_2019_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='tyt_sir_2019_yer',
            field=models.FloatField(default=1, max_length=8, verbose_name='tyt_sir_2019_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='tytham',
            field=models.FloatField(default=500, max_length=3, verbose_name='TYTham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='tytyer',
            field=models.FloatField(default=500, max_length=3, verbose_name='TYTyer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ydtham',
            field=models.FloatField(default=500, max_length=3, verbose_name='Ydtham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ydtyer',
            field=models.FloatField(default=500, max_length=3, verbose_name='Ydtyer'),
        ),
    ]
