# Generated by Django 3.0.8 on 2020-08-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YKS', '0005_auto_20200816_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_ea_2018_ham',
            field=models.IntegerField(default=1, verbose_name='ayt_sir_ea_2018_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_ea_2018_yer',
            field=models.IntegerField(default=1, verbose_name='ayt_sir_ea_2018_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_ea_2019_ham',
            field=models.IntegerField(default=1, verbose_name='ayt_sir_ea_2019_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_ea_2019_yer',
            field=models.IntegerField(default=1, verbose_name='ayt_sir_ea_2019_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sayisal_2018_ham',
            field=models.IntegerField(default=1, verbose_name='ayt_sir_sayisal_2018_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sayisal_2018_yer',
            field=models.IntegerField(default=1, verbose_name='ayt_sir_sayisal_2018_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sayisal_2019_ham',
            field=models.IntegerField(default=1, verbose_name='ayt_sir_sayisal_2019_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sayisal_2019_yer',
            field=models.IntegerField(default=1, verbose_name='ayt_sir_sayisal_2019_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sozel_2018_ham',
            field=models.IntegerField(default=1, verbose_name='ayt_sir_sozel_2018_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sozel_2018_yer',
            field=models.IntegerField(default=1, verbose_name='ayt_sir_sozel_2018_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sozel_2019_ham',
            field=models.IntegerField(default=1, verbose_name='ayt_sir_sozel_2019_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ayt_sir_sozel_2019_yer',
            field=models.IntegerField(default=1, verbose_name='ayt_sir_sozel_2019_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='tyt_sir_2018_ham',
            field=models.IntegerField(default=1, verbose_name='tyt_sir_2018_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='tyt_sir_2018_yer',
            field=models.IntegerField(default=1, verbose_name='tyt_sir_2018_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='tyt_sir_2019_ham',
            field=models.IntegerField(default=1, verbose_name='tyt_sir_2019_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='tyt_sir_2019_yer',
            field=models.IntegerField(default=1, verbose_name='tyt_sir_2019_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ydt_sir_2018_ham',
            field=models.IntegerField(default=1, verbose_name='ydt_sir_2018_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ydt_sir_2018_yer',
            field=models.IntegerField(default=1, verbose_name='ydt_sir_2018_yer'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ydt_sir_2019_ham',
            field=models.IntegerField(default=1, verbose_name='ydt_sir_2019_ham'),
        ),
        migrations.AlterField(
            model_name='yks',
            name='ydt_sir_2019_yer',
            field=models.IntegerField(default=1, verbose_name='ydt_sir_2019_yer'),
        ),
    ]
