# Generated by Django 3.0.8 on 2020-08-12 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='icerik')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ogrenci')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
