# Generated by Django 3.0.8 on 2020-08-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200812_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogrenci',
            old_name='ogrenci_id',
            new_name='ogrenci',
        ),
    ]
