# Generated by Django 3.0.8 on 2020-08-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200812_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrenci',
            name='context',
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='eaham',
            field=models.TextField(default=500, max_length=3, verbose_name='Eaham'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='eayer',
            field=models.TextField(default=500, max_length=3, verbose_name='Eayer'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='sayisalham',
            field=models.TextField(default=500, max_length=3, verbose_name='Sayisalham'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='sayisalyer',
            field=models.TextField(default=500, max_length=3, verbose_name='Sayisalyer'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='siralamalar',
            field=models.TextField(default='', max_length=200, verbose_name='Siralamalar'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='sozelham',
            field=models.TextField(default=500, max_length=3, verbose_name='Sozelham'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='sozelyer',
            field=models.TextField(default=500, max_length=3, verbose_name='Sozelyer'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='tytham',
            field=models.TextField(default=500, max_length=3, verbose_name='TYTham'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='tytyer',
            field=models.TextField(default=500, max_length=3, verbose_name='TYTyer'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='ydtham',
            field=models.TextField(default=500, max_length=3, verbose_name='Ydtham'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='ydtyer',
            field=models.TextField(default=500, max_length=3, verbose_name='Ydtyer'),
        ),
    ]
