# Generated by Django 3.0.8 on 2020-08-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200812_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ogrenci',
        ),
    ]
